### ISSUE TITLE
Add Canvas

### ISSUE THREAD

**Issue by somebody1234** [ETHproductions/golfing-langs#11]
- Language name: canvas
- Source: https://github.com/dzaima/Canvas
- Creator: dzaima
- Type: Stack-based
- Specialty: ASCII-art
- Docs: https://github.com/dzaima/Canvas/wiki
- Quick-ref: https://github.com/dzaima/Canvas/wiki/The-Basics
- Online interpreter: https://cdn.rawgit.com/dzaima/Canvas/master/index.html

**Comment by ETHproductions** [comment]
Thanks for the info. The quick-ref is supposed to be a reference list of commands, like found at the [dev interpreter](https://dzaima.github.io/Canvas/?dev)--is there any particular reason why you suggested that interpreter instead?

**Comment by somebody1234** [comment]
@ETHproductions :/ not really. I don't think linking to the interpreter would be a nice way to do it, but better than nothing I ugess

**Comment by ETHproductions** [comment]
Added this in, btw. I just linked to the https://dzaima.github.io/Canvas interpreter, and had the quick ref point to the same page with dev mode enabled.
