### ISSUE TITLE
Add Keg

### ISSUE THREAD

**Issue by ghost** [ETHproductions/golfing-langs#13]
- Language name: Keg
- Source: https://github.com/JonoCode9374/Keg
- Creator: [JonoCode9374](https://github.com/JonoCode9374)
- Type: Stack-based
- Specialty: Strings
- Docs: https://esolangs.org/wiki/Keg
- Quick-ref: https://esolangs.org/wiki/Keg#Command_Glossary
- Online interpreter: none

**Comment by ghost** [comment]
You accidentally mispelled Keg as "Peg".

**Comment by ETHproductions** [comment]
I thought something was wrong, sorry about that :P
