### ISSUE TITLE
Add even more languages

### ISSUE THREAD

**Issue by ghost** [ETHproductions/golfing-langs#14]
I [found](https://esolangs.org/wiki/Category:Golfing_language) a few more golfing languages on esolangs.org. I filtered out the unimplemented languages and the useless languages and got these:

- Language name: [Sclipting](https://esolangs.org/wiki/Sclipting)
- Source: https://github.com/Timwi/EsotericIDE
- Creator: [Timwi](https://github.com/Timwi)
- Type: Stack-based
- Specialty: Unknown
- Docs: https://esolangs.org/wiki/Sclipting
- Quick-ref: https://esolangs.org/wiki/Sclipting
- Online interpreter: None
<hr>

- Language name: [Microscript](https://esolangs.org/wiki/Microscript)
- Source: https://esolangs.org/wiki/Microscript
- Creator: [SuperJedi224](https://esolangs.org/wiki/User:SuperJedi224)
- Type: Stack-based
- Specialty: Unknown
- Docs: https://github.com/SuperJedi224/Microscript
- Quick-ref: https://github.com/SuperJedi224/Microscript
- Online interpreter: None
<hr>

- Language name: [Microscript](https://esolangs.org/wiki/Microscript_II)
- Source: https://esolangs.org/wiki/Microscript_II
- Creator: [SuperJedi224](https://esolangs.org/wiki/User:SuperJedi224)
- Type: Stack-based
- Specialty: Unknown
- Docs: https://github.com/SuperJedi224/Microscript-II
- Quick-ref: https://github.com/SuperJedi224/Microscript-II
- Online interpreter: None
<hr>

- Language name: [Gulf](https://esolangs.org/wiki/Gulf)
- Source: https://github.engineering.zhaw.ch/munt/Gulf
- Creator: [munt](https://github.engineering.zhaw.ch/munt)
- Type: etc.
- Specialty: Unknown
- Docs: https://github.engineering.zhaw.ch/munt/Gulf/blob/master/DOC.TXT
- Quick-ref: https://github.engineering.zhaw.ch/munt/Gulf/blob/master/DOC.TXT
- Online interpreter: None

**Comment by Areallycoolusername** [comment]
I almost named Gulp, Gulf... It's a good thing I didn't.
