### ISSUE TITLE
Add FOG

### ISSUE THREAD

**Issue by somebody1234** [ETHproductions/golfing-langs#6]
- Language name: Fuzzy-Octo-Guacamole
- Source: https://github.com/RikerW/Fuzzy-Octo-Guacamole
- Creator: RikerW, full name [here](https://github.com/RikerW/Fuzzy-Octo-Guacamole/blob/master/main.py)
- Type: Stack-based
- Specialty: None (AFAIK)
- Docs: [GitHub Wiki](https://github.com/RikerW/Fuzzy-Octo-Guacamole/wiki)
- Quick-ref: See docs
- Online interpreter: None

**Comment by ETHproductions** [comment]
Completed in 771f462. Thank you!
