### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by somebody1234** [ETHproductions/golfing-langs#8]
## Jellyfish

- Language name: Jellyfish
- Source: https://github.com/iatorm/jellyfish
- Creator:  Ilkka Törmä
- Type: Two-dimensional
- Specialty: None
- Docs: https://github.com/iatorm/jellyfish/blob/master/doc.md
- Quick-ref: See docs
- Online interpreter: https://tio.run/nexus/jellyfish

## Autovim
- Language name: Autovim
- Source: https://github.com/christianrondeau/autovim
- Creator: Christian Rondeau
- Type: Imperative
- Specialty: 2D strings
- Docs: https://github.com/christianrondeau/autovim/tree/master/doc
- Quick-ref: https://github.com/christianrondeau/autovim/blob/master/doc/tutorial.md
- Online interpreter: None

## Fireball

- Language name: Fireball
- Source: https://github.com/okx-code/Fireball
- Creator: [Okx](https://github.com/okx-code)
- Type: Stack-based
- Specialty: None
- Docs: https://github.com/okx-code/Fireball/wiki
- Quick-ref: See docs
- Online interpreter: None

## ShinyLisp

- Language name: ShinyLisp
- Source: https://github.com/Mercerenies/shiny-lisp
- Creator: [Silvio Mayolo](https://github.com/Mercerenies)
- Type: Lisp-based (Haskell derivative)
- Specialty: None
- Docs: None
- Quick-ref: None
- Online interpreter: None

## GolfASM

- Language name: GolfASM
- Source: https://github.com/alexj136/GolfASM
- Creator: [Alex Jeffery](https://github.com/alexj136)
- Type: Unknown
- Specialty: None
- Docs: None
- Quick-ref: None
- Online interpreter: None

There sure are a lot of golflangs named after food:

## Noodel

- Language name: Noodel
- Source: https://github.com/tkellehe/noodel
- Creator: [tkellehe](https://github.com/tkellehe)
- Type: Stack-based
- Specialty: ASCII art animation
- Docs: https://github.com/tkellehe/noodel/tree/master/docs
- Quick-ref: https://github.com/tkellehe/noodel/blob/master/README.md
- Online interpreter: https://tkellehe.github.io/noodel/editor.html

## Carrot

- Language name: Carrot
- Source: https://github.com/kritixilithos/Carrot
- Creator: [Kritixi Lithos](https://github.com/kritixilithos)
- Type: Stack-based
- Specialty: None
- Docs: https://github.com/kritixilithos/Carrot/wiki
- Quick-ref: See docs
- Online interpreter: http://kritixilithos.github.io/Carrot/

**Comment by ETHproductions** [comment]
Thanks for all the info! I've added all of these to the list.

On a side note, I didn't think it was possible to create a 2-dimensional golfing language. Boy was I wrong...
